@DukaUrl=http://localhost:7071/api

GET {{DukaUrl}}/GetSubscriptions
```

###

POST {{DukaUrl}}/RegisterSubscriptions

###
POST {{DukaUrl}}/ClearSubscriptions
```


###

GET {{DukaUrl}}/GetOnlineChannels

###

POST {{DukaUrl}}/ResolveChannelId

###
POST {{DukaUrl}}/ResolveUserId

###
POST {{DukaUrl}}/SubscriptionCallBack


